package com.example.myapplication.ai.conversation

enum class ConversationRoute {
    TASK_COMMAND,
    SMART_ROUTINE_BUILDER,
    SAVED_ROUTINE_ACTION,
    DAILY_BRIEFING,
    CONTEXT_AWARE_SUGGESTION,
    CONTEXT_READ,
    CONTEXT_ACTION,
    QUERY_READING_CONTROL,
    SETTINGS_ACTION,
    SETTINGS_READ,
    DIRECT_REPLY,
    ASK_CLARIFICATION,
    END_SESSION,
    UNKNOWN
}
